#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>   

/*****************************************************************************************
* SIMPLE FILE ENCRYPTION PROGRAM
*
* This program takes an input file and encrypts it based on a hash generated by djb2.
* 
* NOTE: 
* Encrypt and decrypt files using the same program.
*
* You can encrypt the input file into whatever format you like, however you must decrypt
* the output back into the same format as the original input file to get readable results,
* assuming your password is correct.
* 
* On decryption, the program will not tell you if your password is the same as the one
* used to generate the encrypted file. It will generate an output file regardless.
*
* PASSWORD LENGTH:
* The longer the password is, the more secure your file becomes.
* Short passwords can be cracked in seconds.
*
* Compile: 
* 	cc encryptFile.c -o encryptFile
*
* Run:
* 	./encryptFile [input file] [output file]
*
* Example:
* 	./encryptFile input.txt output.txt
*
* Author: Haran Lakha
*****************************************************************************************/

/***********************************************************************
* Title: djb2 hash algorithm
* Author: Bernstein, Daniel J. (aka djb)
* Year: 1991
* Code taken from: http://www.cse.yorku.ca/~oz/hash.html
* Original Source: https://groups.google.com/g/comp.lang.c/c/lSKWXiuNOAk
***********************************************************************/

unsigned long djb2(unsigned char *str){

	unsigned long hash = 5381;
    int c;

    while (c = *str++){
    	hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
	}

   	return hash;
}

/*********************************************
* Title: Echo blank password function
* Author: Gouveia, H.
* Year: 2016
* Source: https://stackoverflow.com/a/39792014
*********************************************/

void echoBlankPassword(char *password){

    static struct termios oldTerminal;
    static struct termios newTerminal;

    //get settings of the actual terminal
    tcgetattr(STDIN_FILENO, &oldTerminal);

    // do not echo the characters
    newTerminal = oldTerminal;
    newTerminal.c_lflag &= ~(ECHO);

    // set this as the new terminal options
    tcsetattr(STDIN_FILENO, TCSANOW, &newTerminal);

    if (fgets(password, BUFSIZ, stdin) == NULL){
    	password[0] = '\0';
    } else{
    	password[strlen(password)-1] = '\0';
    }

    // go back to the old settings
    tcsetattr(STDIN_FILENO, TCSANOW, &oldTerminal);
}

int encryptFile(char *input, char *output, char *password){

	FILE *inputFile, *outputFile;
	int i;
	
	unsigned long hashed = djb2(password);
	
	inputFile = fopen(input, "r");
	outputFile = fopen(output, "w");
	
	if(inputFile == NULL){
		printf("Can't open input file!");
		return -1;
	}
	
	while((i = getc(inputFile)) != EOF){
		putc(i ^ hashed, outputFile);
	}
	
	fclose(inputFile);
	fclose(outputFile);
	
	return 0;
}

int main(int argc, char **argv){
	
	char password[BUFSIZ];
	char secondPass[BUFSIZ];
	
	puts("Insert password:");
	echoBlankPassword(password);
	
	puts("Confirm password:");
	echoBlankPassword(secondPass);

	
	if(argc == 3 && strcmp(password, secondPass) == 0){
		encryptFile(argv[1], argv[2], password);
	} else if(argc == 3 && strcmp(password, secondPass) != 0){
		printf("Passwords do not match!\nEncryption aborted.\n");
		return -1;
	} else{
		printf("Please use input format: ./encryptFile [input file] [output file]\n");
	}
	
	return 0;
}
